# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.16.0"

default_platform :ios

platform :ios do

	desc "Builds the framework and runs all the tests"
	lane :test do

		# Working around a timeout issue
		ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "120" 

		# Build and test
		scan(
			workspace: "Example/Yakka.xcworkspace",
			scheme: "Yakka-Example",
			devices: [
				"iPhone SE",
				"iPhone 6",
				"iPhone 7 Plus"
			],
			clean: true,
			skip_slack: true
		)
	end
end
